### ISSUE TITLE
Comparing with lvalues does  not work anymore

### ISSUE THREAD

**Issue by githubuser0xFFFF** [DuffsDevice/tiny-utf8#23]
Hi,

the following code that compiled with an older tinyutf8 version now generates a compile error with MinGW 7.3.0:

```
utf8_string teststring = "µm";
if (teststring == "µm")
{
 
}
```
The following error is generated:

```
In file included from ../src/Widget.cpp:3:0:
tinyutf8.h: In instantiation of 'int utf8_string::compare(const char (&)[LITLEN]) const [with unsigned int LITLEN = 4]':
tinyutf8.h:1866:111:   required from 'bool utf8_string::operator==(const char (&)[LITLEN]) const [with unsigned int LITLEN = 4]'
../src/Widget.cpp:55:23:   required from here
tinyutf8.h:1809:10: error: increment of read-only location '(const char*)str'
    ++it, ++str;
          ^~~~~
tinyutf8.h:1809:10: error: lvalue required as increment operand
```

**Comment by DuffsDevice** [comment]
Is the error fixed with the latest revision?

**Comment by DuffsDevice** [comment]
Note, that revision 34a1ef51d38571cd54189edc87ef8008dfd3f992 still contains a compilation error, so try the latest one.

**Comment by DuffsDevice** [comment]
And feel free to re-open the issue any time 😃

**Comment by githubuser0xFFFF** [comment]
Hi,

thank you for the quick fix. I tested the latest changes. The compile error is gone but the comparison does not work properly:

The following code:

```cpp
    utf8_string teststring = "µm";
    if (teststring == "µm")
    {
    	std::cout << "teststring != µm --> true" << std::endl;
    }

    if (teststring == utf8_string("µm"))
    {
    	std::cout << "teststring != utf8_string(\"µm\") --> true" << std::endl;
    }
```
produces the following output:

`teststring != utf8_string("µm") --> true`

So the comparison with the string constant fails.
