### ISSUE TITLE
Unable to compile under VS

### ISSUE THREAD

**Issue by linwe2012** [DuffsDevice/tiny-utf8#25]
I'm trying to replace `std::string` with `utf8string`. But some problem occurs:
- at line 4336 in `tinyutf8.h`,  gives error C4146 unary minus operator applied to unsigned type, result still unsigned
- afteri tried fixing the previous problem another occurs: C4703 potentially uninitialized local pointer variable 'app_lut_base_ptr' used	tinyutf8.h	3134	
- also there are about 70 warnings. Could you fix them all?
- some operators are not overloaded as in `std::string`:
   - `operator+=(char )`
   - `operator+(const char*, string)`

I am using VS2019, and c++ standard is 17, warning level is 4

**Comment by DuffsDevice** [comment]
Hi There!,

Concerning the error, I will try to fix that one as soon as I have the time to, I guess within the next few days 😃 Same goes for `operator+=` overloads.
Could you paste your compilation output into this issue? THis way, I can understand the issues better and make sure I fix all errors in the first place, so you can start working.

All the Best,
Jakob

**Comment by DuffsDevice** [comment]
Did you get my message?
