### ISSUE TITLE
too many warnings when compiling

### ISSUE THREAD

**Issue by nelyubin-ev** [DuffsDevice/tiny-utf8#32]
![image](https://user-images.githubusercontent.com/3295141/71551040-05598500-2a29-11ea-8a7c-0a1b5d8d101a.png)

**Comment by DuffsDevice** [comment]
Hi there,
I just opened tinyutf8.h and checked the line numbers. However I cannot see why they should issue this warning. Could you plz Check whether you have the latest version of this file or copy&paste the corresponding lines of code here?
Thanks,
Jakob

**Comment by nelyubin-ev** [comment]
line numbers with latest version of lib
![image](https://user-images.githubusercontent.com/3295141/71637913-92584480-2c9c-11ea-830a-435b3d6436ef.png)

**Comment by DuffsDevice** [comment]
Thanks! Please check to see, if the issue is now solved. Feel free to reopen the ticket if not 😊
