### ISSUE TITLE
Support for u8 string literal changes in c++20

### ISSUE THREAD

**Issue by revel8n** [DuffsDevice/tiny-utf8#34]
In c++20 u8 string literals no longer default to const char[N], instead becoming const char8_t[N].

Since there are currently no explicit conversions to or from char8_t*, u8string, etc., examples like the one proposed in the readme (using u8"" string literals) no longer compile successfully when configured to use the latest standard.

the __cpp_char8_t and __cpp_lib_char8_t macros could possibly be used to determine support for the extended types.

**Comment by DuffsDevice** [comment]
Hello,
Thank you for your heads-up regarding char8_t in C++20.
I'll implement the changes you suggest 👍, it might take me a week or so.
Best Regards,
Jakob

**Comment by DuffsDevice** [comment]
Hi again,
as it turns out, I am so busy with university, I won't make it within two weeks or so. If you like, please submit a pull request implementing the necessary changes.
Thanks,
Jakob
PS: I will still try to do it as soon as I get the chance to.

**Comment by DuffsDevice** [comment]
I'm gonna close it for now. Feel free to reopen the ticket in case you need to :)
