### ISSUE TITLE
Incorrect codepoint size calculation on processors that do not support 'lzcnt'

### ISSUE THREAD

**Issue by revel8n** [DuffsDevice/tiny-utf8#35]
https://github.com/DuffsDevice/tiny-utf8/blob/4fc49c8cbeb1cd6cd77bcc84113986cda510b200/tinyutf8.h#L82

On processors that do no support the 'lzcnt' instruction this intrinsic will be interpreted incorrectly as 'bsr' (BitScanReverse) thus giving the bit index instead of the count of leading zeros.

This in turn causes the calculations for codepoint sizes to be incorrect when used in encoding and decoding operations.

If a suitable alternative is not available sources i have seen recommend basing 'clz' on BitScanReverse instead.

**Comment by revel8n** [comment]
It looks like this is related to issues with lzcnt usage on processors that do not support the instruction.

They will be interpreted as bsr (BitScanReverse) instead which gives the bit position instead of the count.

**Comment by DuffsDevice** [comment]
I see, thank you for pointing me to this issue. How would that work to use BitScanReverse?
May I ask you to submit a pull request?

Let me know 🙋‍♂
Jakob

**Comment by DuffsDevice** [comment]
Fixed through #36
