### ISSUE TITLE
C++17 compiler required

### ISSUE THREAD

**Issue by githubuser0xFFFF** [DuffsDevice/tiny-utf8#37]
When compiling or using the library with C++11 or C++14 MSVC17 build fails with the following error:

`error C2429: Attribute "fallthrough" requires the compiler identification "/std:c++17"`

The documentation of your project states: 
>Tiny-utf8 is a library for extremely easy integration of Unicode into an arbitrary C++11 project

Is the bug in the documentation or in the code? Would be great if this library could be used with C++11

**Comment by DuffsDevice** [comment]
Hi there,

thank you for your issue!
A valid C++11 compiler is asked to process only attributes it knows and ignore the ones it doesn't.
That means, something in your command line or perhaps within msvc turns warnings into errors.
Maybe you wanna have a look at that. Tinyutf8 should be valid C++11.
I excuse for the time it took me to reply.

All the best,
Jakob

**Comment by DuffsDevice** [comment]
I assume, the Issue is not relevant anymore.

**Comment by githubuser0xFFFF** [comment]
Hi Jakob,

thank you for your reply. I will try to find a compiler switch in MSVC17 to make it compile.

And btw. thank you for this great library.

**Comment by DuffsDevice** [comment]
Hey there!

Thanks for letting me know. Good luck to you!
I hope you succeed, otherwise it might be possible to put #if's around the attributes :)

Thank you for your kind words :)

Jakob
