### ISSUE TITLE
Please consider vcpkg support

### ISSUE THREAD

**Issue by MattHarrington** [DuffsDevice/tiny-utf8#39]
`vcpkg` includes an older version of `tiny-utf8`: https://github.com/microsoft/vcpkg/tree/master/ports/tinyutf8.  Would you consider making pull requests there to keep the version in `vcpkg` up to date?

Many people know about `vcpkg` already, but for those who don't it's a cross-platform package manager.  It's open source.  It works with macOS, Linux, Windows, gcc, clang, MSVC, and probably other combinations of OSes and compilers.  It's terrific for discovering libraries.  That's how I found `tiny-utf8`.

**Comment by DuffsDevice** [comment]
Dear Matt,
how would that work? I have never used vcpkg before.
I'd be so happy, if you could update the version in vcpkg appropriately as I have no clue yet on how that works.
What do you think?

Jakob

**Comment by MattHarrington** [comment]
I can't help you with `vcpkg`, but since your library is already included, it's just a matter of getting it updated.

This CppCon 2018 talk is probably worth watching:

[CppCon 2018: Robert Schumacher “Don't package your libraries, write packagable libraries!”](https://www.youtube.com/watch?v=sBP17HQAQjk&t=5s)

`vcpkg` is very much worth knowing.

**Comment by DuffsDevice** [comment]
Thank you Matt for the link. I just watched the video and I have to say, I do like it a lot :)
I will ask one of the people that added tiny-utf8 to update it accordingly. I hope they have the time to do so.
Otheriwse I might figure it out myself.

**Comment by DuffsDevice** [comment]
Hi Evan, do you have any experience in packaging for vcpkg? I don't even have Visual Studio so I'm having a hard time wrapping my head around it as I wouldn't even be able to try it out once I did.

**Comment by MattHarrington** [comment]
Oh, you don't need Visual Studio.  You don't need Windows.  They probably should have named it something other than `vcpkg`.  It has no dependency on any Microsoft products.

**Comment by evanmoran** [comment]
I haven't updated vcpkg myself, but I think @MattHarrington is right that it can be done without Visual Studio and just needs vcpkg and cmake to test.

Here's how you get vcpkg installed locally: https://github.com/microsoft/vcpkg#getting-started

Once you install vcpkg you can run `vcpkg install tinyutf8` to install / build your package. I don't know how to author a new package, but I know they have tons of pull requests to update them so it's quite common. 

And here's a link to the initial commit that added tinyutf8 in the first place: https://github.com/Microsoft/vcpkg/pull/4388/files
And here's the directory of the current ported version (3.0.1): https://github.com/Microsoft/vcpkg/tree/master/ports/tinyutf8

**Comment by evanmoran** [comment]
ok, well after all that I'm apparently an expert haha :). It looks like you might only need to change the commit hash in https://github.com/microsoft/vcpkg/blob/master/ports/tinyutf8/portfile.cmake, and the version in https://github.com/microsoft/vcpkg/blob/master/ports/tinyutf8/CONTROL

**Comment by DuffsDevice** [comment]
When I try to install vcpkg it tells me that Visual Studio 2015 or higher is missing to compile vcpkg...
Do I really need to get it? Currently I'm using a MinGW based toolchain.

**Comment by evanmoran** [comment]
You may on windows? Not sure! The visual studio 2019 community addition is
free and has everything you need if you want to try

**Comment by iainchesworth** [comment]
I've raised a PR (now merged into master) that updates the vcpkg port from v3.0.1 to v4.0.2.  See https://github.com/microsoft/vcpkg/pull/13706.

**Comment by evanmoran** [comment]
Very cool. Thank you!

**Comment by MattHarrington** [comment]
@DuffsDevice It sounds like you're on Windows.  Correct?

**Comment by DuffsDevice** [comment]
Correct!
