### ISSUE TITLE
Allocator support. 

### ISSUE THREAD

**Issue by pr8x** [DuffsDevice/tiny-utf8#42]
It would be greate to get allocator support. (Possibly even PMR).

**Comment by DuffsDevice** [comment]
Hi Luis,

Good news! I committed a draft for allocator support.
My example compiles finely, but I don't know about your use case. Could you check and tell me, whether it compiled finely and worked?

Yours,
Jakob

**Comment by pr8x** [comment]
Hey, cool thanks for the quick response!
I didn't build the library yet locally. We're currently evaluating Unicode libraries and the lack of allocator support was somewhat of a disadvantage for us. Good to see it implemented now. Inheriting from the allocator for EBO is a bit unconventional, but I guess including a full-blown compressed_pair is overkill here. 

My use case would primarily be pmr. So maybe, if you have spare time, you could test it with `std::polymorphic_allocator<>` and `std::monotonic_buffer_resource<>`. If it works with `std::allocator` it should work with pmr just fine!

Cheers

**Comment by DuffsDevice** [comment]
Sure! I happened to have the time 😃

That's what I figured, inheriting does work very well for now I guess :)
PMR should work quite well 👍

Cheers,
Jakob

**Comment by DuffsDevice** [comment]
FYI: Right now, I fixed several bugs that I had not seen before (related to allocators).

**Comment by DuffsDevice** [comment]
I will close this ticket for now. If you should encounter any issues. Feel free to open it again ;)
