### ISSUE TITLE
Grapheme cluster

### ISSUE THREAD

**Issue by pr8x** [DuffsDevice/tiny-utf8#43]
Any plans to add support for iterating not just code points but also [grapheme cluster](https://unicode.org/reports/tr29/)?

**Comment by DuffsDevice** [comment]
Hi there! Thanks for you message :)

In principle, it is rather easy to extend tiny-utf8 to incorporate custom segmentation metrics and value types (e.g. grapheme cluster). However, as you may know, grapheme clusters require huge lookup tables that tiny-utf8 cannot provide as a service.

Do you have an idea on how to incorporate the lookup tables from e.g. ICU?
I have to little knowledge about how ICU works right now, to work on the topic.

But I definitely am in favor of your idea!

Best Regards,
Jakob
