### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by vfiksdal** [DuffsDevice/tiny-utf8#44]
Hi,
Havent used tinyutf8 much yet, but it is looking promising :-)

Anyway, I try to crosscompile a windows program using x86_64-w64-mingw32-g++ and get the following error in the included header file:

src/tinyutf8.h: In instantiation of ‘tiny_utf8::basic_utf8_string<ValueType, DataType, Allocator>& tiny_utf8::basic_utf8_string<ValueType, DataType, Allocator>::operator=(tiny_utf8::basic_utf8_string<ValueType, DataType, Allocator>&&) [with ValueType = char32_t; DataType = char; Allocator = std::allocator<char>]’:
src/carchive.cpp:33:43:   required from here
src/tinyutf8.h:1216:18: error: invalid cast from type ‘tiny_utf8::basic_utf8_string<char32_t, char>::SSO’ to type ‘void*’
 1216 |     std::memcpy( (void*)this->t_sso , (void*)&str.t_sso , sizeof(SSO) ); // Copy data

Changing to &this->t_sso allows compilation, but is this a sane thing to do?

**Comment by DuffsDevice** [comment]
Hey there,

Thank you for your message! It is exactly what's necessary 😉
I have fixed the issue in the latest commit. I will close this ticket for now, but feel free to reopen it again anytime.

Greetings,
Jakob
