### ISSUE TITLE
Empty std::string problem

### ISSUE THREAD

**Issue by vfiksdal** [DuffsDevice/tiny-utf8#45]
I have tried experimenting in a couple of classes in an existing project,. but have some strange issues when combining it with empty std::string objects. In the test below I expect all printf's to be empty, but I seem to get unterminated gibberish at b and d on linux, and b on windows.

#include "tinyutf8.h"

using namespace tiny_utf8;

int main(){
    std::string stdstring="This is a string";
    utf8_string utfstring="This is a string";
    std::string a=stdstring.substr(stdstring.length());
    utf8_string b=stdstring.substr(stdstring.length());
    utf8_string c=utfstring.substr(utfstring.length());
    utf8_string d=std::string("");
    utf8_string e="";
    printf("a=%s\r\n",a.c_str());
    printf("b=%s\r\n",b.c_str()); // Fails
    printf("c=%s\r\n",c.c_str());
    printf("d=%s\r\n",d.c_str()); // Fails
    printf("e=%s\r\n",e.c_str());
}

Thanks for a really nice library though :-)

**Comment by DuffsDevice** [comment]
Hi again,

thank you so much for the incredibly easy-to-trace bug report!
You made it really easy to fix the issue.
It was very simple and introduced by the allocator support addition.
Please tell me if it works now :)

Thank you, I appreciate it a lot!

All the best,
Jakob

**Comment by vfiksdal** [comment]
Thanks for the fast response. Pulled the latest update, and it works great!

**Comment by DuffsDevice** [comment]
Great to hear that!
