### ISSUE TITLE
How to use the bidi algorithm with TinyUTF8?

### ISSUE THREAD

**Issue by srvasn** [DuffsDevice/tiny-utf8#46]
TinyUTF8 is awesome, however, I am using it in a project where I encounter bidirectional text (Arabic + English) frequently, which is not represented correctly by TinyUTF8. Is there any way to use the bidi algorithm with TinyUTF8's string class?

**Comment by DuffsDevice** [comment]
Hi Sourav,

thank you for your Message!

As you probably already guessed, tiny-utf8 only does the detection of codepoint boundaries within UTF-8 encoded data. When you iterate your string, it is iterated from the first codepoint to the last (in the data), not the "leftmost" to the "rightmost". The bidi algorithm strictly speaking is a higher abstraction level than the one of codepoints (what tiny utf8 does) but at the same time requires a codepoint abstraction level. Therefore, tiny-utf8 is a viable foundation to implement the bidi algorithm on but the bidi algorithm is not in scope of it.

I hope, this answeres your question at least in the sense to what extent tiny-utf8 can meet your needs for this use case. If you have further questions, I'm happy to help you.

All the Best,
Jakob

**Comment by srvasn** [comment]
Thanks a lot for the response. I have managed to solve my problem.

I was working on a unicode compliant text rendering engine for that I was using to render text in OpenGL ES. The target platform was Android where I had access to the ICU C API only (no UnicodeString :( ) owing to https://github.com/android/ndk/issues/548.

What I ended up doing was using TinyUTF8 as a container for my string while still using ICU for the bidi conversions. It worked out really well!

Maybe I'll do a pure bidi implementation soon using TinyUTF8 in the near future. Thanks a lot for your awesome project!

**Comment by DuffsDevice** [comment]
I'm very glad to hear you got it done! I would be very interested in how you got it done. Sounds like a great solution!
If you feel like it, I'd be happy to understand how you got it done. Thanks anyway for your encouraging message :)
Makes me happy to hear my project helped you.

Cheers!

**Comment by DuffsDevice** [comment]
I just closed it for now, as it is not an open "issue" :)
