### ISSUE TITLE
Unexpected push_back result

### ISSUE THREAD

**Issue by alexeyr** [DuffsDevice/tiny-utf8#48]
```
#include <iostream>
#include <cstdlib>
#include "tinyutf8.h"

int main()
{
    tiny_utf8::utf8_string str;
    str.push_back(U'a');
    std::cout << str.size() << "\n" << str[0] << "\n" << str << "\n\n";

    std::string str1;
    str1.push_back('a');
    std::cout << str1.size() << "\n" << str1[0] << "\n" << str1 << "\n";
}
```
outputs
```
1
a
a
``` 
for the `std::string` as expected, but
```
1
0

```
for `tiny_utf8::utf8_string` (using Clang 10). It seems `\0` is getting appended instead of `a`.

**Comment by DuffsDevice** [comment]
Hi Alexey,

Thank you for the bug report and for the minimal example. It made it really easy for me to spot the bug!
I just fixed the issue in the last commit 😃

Cheers,
Jakob
