### ISSUE TITLE
C++20 

### ISSUE THREAD

**Issue by ReeceSX** [DuffsDevice/tiny-utf8#52]
Hello, 

C++20 introduced new helper functions ends_with and starts_with, are there any plans to add partial or full support for modern std::basic_string_view operators and utils?

**Comment by DuffsDevice** [comment]
Hi Reece,

thanks for your message. ends_with and start_with are trivial to implement and I will do so in the next few days. Providing a non-owning string view is rather huge. It was and probably will be as much work as I needed for providing allocator support.
As you are not the first person to ask it, I do plan to implement it, only perhaps not very soon.

Cheers,
Jakob

**Comment by DuffsDevice** [comment]
Added starts_with and ends_with in PR #54 
:)
