### ISSUE TITLE
MSVC x86: error C3861: '_BitScanReverse64': identifier not found

### ISSUE THREAD

**Issue by maddouri** [DuffsDevice/tiny-utf8#56]
Hello Jakob,

Well done on solving #55 so quickly!

Here is a new issue that I found when trying out the readme code sample on 32bit versions of MSVC.

Example at https://godbolt.org/z/Peh1xq with MSVC 2017 and commit 411dfba7be72717f77e2f3e953469c43634af824

```
tinyutf8.h(152): error C3861: '_BitScanReverse64': identifier not found
tinyutf8.h(158): note: see reference to function template instantiation 'unsigned int tiny_utf8::tiny_utf8_detail::lzcnt<uint16_t>(T) noexcept' being compiled

        with
        [
            T=uint16_t
        ]
```

Thanks :)

**Comment by DuffsDevice** [comment]
Hi again :)

Thanks! I'm glad it works for you now!
Your example should work now. It was solely due to a non-robust check for 32bit Windows...

Cheers,
Jakob
