### ISSUE TITLE
append() method with value_type

### ISSUE THREAD

**Issue by vadim-berman** [DuffsDevice/tiny-utf8#57]
Hi Jakob,

Hope things are well! A minor issue with an `append(value_type)` method and the `+=` operator overload. It does not concatenate non-ASCII characters properly. Example: 

```
    utf8_string badAppend;
    utf8_string::value_type v1 = U'“', v2 = U'a', v3 = U'b', v4 = U'à', v5 = U'”';
    badAppend += v1;
    badAppend += v2;
    badAppend += v3;
    badAppend += v4;
    badAppend += v5;
    cout << badAppend << endl;
    cout.flush();
```

You get something like `&&&&&`. Funny enough, it does not happen in Debug mode, which makes me think whether some sort of a local variable was not initialized properly. 

My workaround is:

```
badAppend += ' ';
badAppend[badAppend.length() - 1] = my_char;
```

**Comment by DuffsDevice** [comment]
Hi Vadim,

Thanks for your message! Sorry to have not replied earlier.
I'm checking it out right now. Letting you know, when its fixed :)

Jakob

**Comment by DuffsDevice** [comment]
Hi Vadim,
for some reason, I was not able to reproduce the issue on my side.
However, I already have a guess on what it might be. Please tell me, whether the branch [issue_57_fix](https://github.com/DuffsDevice/tiny-utf8/tree/issue_57_fix)
works for you!

**Comment by vadim-berman** [comment]
Hi Jakob,

Thank you! I'll take a look over the next few days.

**Comment by vadim-berman** [comment]
Hi Jakob,

Thank you! Appears to be working.

**Comment by DuffsDevice** [comment]
Nice, thanks for your message! Glad it works now!
