### ISSUE TITLE
Is it possible to do case-insensitive comparison with the tiny-utf8?

### ISSUE THREAD

**Issue by siavee** [DuffsDevice/tiny-utf8#60]
Hi, is it possible to do case-insensitive comparison with tiny-utf8?

Basically what this question on SO is asking: https://stackoverflow.com/questions/11635/case-insensitive-string-comparison-in-c.

I'm trying to avoid using ICU in my app.

Thanks!

**Comment by DuffsDevice** [comment]
Hi there,

tiny-utf8 is a container for utf8-encoded unicode codepoints. It has no insights into the meaning of certain codepoint values.
In principle, what is necessary to compare two strings (=two codepoint values) case-insensitively is a Database of Codepoints and their relations (e.g. x is uppercase of y, and so on). I'm sorry, tiny-utf8 was not built for this task. ICU provides such a database.

However, once you have figure out how to compare two codepoints case-insensitively, you can do the following:

```cpp
tiny_utf8::string str1, str2;
bool is_same = std::equal( str1.begin() , str1.end() , str2.begin() , str2.end() , []( char32_t cp1 , char32_t cp2 ){
    return codepoint_insensitive_compare( cp1 , cp2 );
} );
```

Good luck with your

**Comment by siavee** [comment]
Hi Jakob,

Thank you very much for your answer, it's very clear. Also I'd also like to thank you for such a wonderful library, it has helped me a lot!

Thanks again!

Avi

**Comment by DuffsDevice** [comment]
Hi Avi,

Yes, sure! Thank you for your words, I'm happy to hear that it has served you.
And it really is my pleasure! It is messages like yours that remind me of why I'm doing this 😊

Jakob
