### ISSUE TITLE
erase-remove idiom does not work as expected

### ISSUE THREAD

**Issue by Abdullah-AlAttar** [DuffsDevice/tiny-utf8#61]
Not sure if I am doing something wrong.
Given the following code it deletes the last character 'd' instead of 'W'. replacing with std::string works fine.
```cpp
#include <tinyutf8/tinyutf8.h>

#include <algorithm>
#include <iostream>


int main()
{
    tiny_utf8::string str = u8"Hello 🌍 World";

    std::cout << str << std::endl;
    // Hello 🌍 World
    str.erase(std::remove_if(str.begin(), str.end(), [](auto c) { return c == U'W'; }),
              str.end());

    std::cout << str << std::endl;
    // Hello 🌍 Worl
}
```

**Comment by Abdullah-AlAttar** [comment]
Thanks for the fix, but there are still some issues.
it is repeating some characters
```cpp
#include <tinyutf8/tinyutf8.h>
#include <algorithm>
#include <iostream>

int main()
{
    tiny_utf8::string str = "!مرحبا !! بكم!";

    std::cout << str << std::endl;

    str.erase(std::remove_if(str.begin(), str.end(), [](char32_t c) { return c == U'!'; }),
              str.end());
    std::cout << str << std::endl;
    // output is : ممرحبا  بببكم!
    // should be مرحبا بكم
}
```

Also here it goes in an infinite loop.
```cpp
#include <tinyutf8/tinyutf8.h>

#include <algorithm>
#include <iostream>


int main()
{
    tiny_utf8::string str = "مرحبا !! بكم!";

    std::cout << str << std::endl;

    str.erase(std::remove_if(str.begin(), str.end(), [](char32_t c) { return c == U'!'; }),
              str.end());
              
    std::cout << str << std::endl;

}
```

**Comment by DuffsDevice** [comment]
Hi Abdullah,

thank you for your messages. Could you checkout the newest commit and see if it did fix your issues?
The problem was: iterators used to point to byte indices and not codepoint indices: therefore `str.end()` may not point to the end of the resulting string at the end of the remove_if(as it might as well be shorter or longer, i.e. contain less/more bytes).

I duplicated the set of iterators for raw (byte-based) and non-raw (codepoint-based) versions. This should fix your issues now :)

Please let me know!

Jakob

**Comment by Abdullah-AlAttar** [comment]
Hi Jakob

just checked after the changes
for the first code snippet. the there still some duplicate characters and it is not removing the last occurrence of '!'
```cpp
    tiny_utf8::string str = "!!مرحبا !! بكم!";
    std::cout << str << std::endl;

    str.erase(std::remove_if(str.begin(), str.end(), [](char32_t c) { return c == U'!'; }),
              str.end());
    std::cout << str << std::endl;
   // مرحبا  بكمم!
```


For the second one. it is not hanging any more. but there are still issues with the output. (getting this weird symbol �) and not removing the last occurrence as well
```
#include <tinyutf8/tinyutf8.h>

#include <algorithm>
#include <iostream>


int main()
{
    tiny_utf8::string str = "مرحبا !! بكم!";

    std::cout << str << std::endl;

    str.erase(std::remove_if(str.begin(), str.end(), [](char32_t c) { return c == U'!'; }),
              str.end());
              
    std::cout << str << std::endl;
    // مرحبا  بكم�!
}
```

**Comment by DuffsDevice** [comment]
I'll close this for now, please feel free to re-open, if the issue should still persist 😃

**Comment by DuffsDevice** [comment]
Oh, dang it, you probably wrote me the second before I closed the ticket 😄 
I will have a look at it! Thanks for your answer!

**Comment by DuffsDevice** [comment]
I fixed it again in the latest commit. Thank you for bearing with me ;)
Please let me know, if it works now.

**Comment by Abdullah-AlAttar** [comment]
Works as expected, thanks for the quick response. and this awesome library.

**Comment by DuffsDevice** [comment]
NICE, happy that it works now! 💪
Thanks for your feedback, I appreciate it!
