### ISSUE TITLE
`cpp_str()` impossible to be used with `u8string`

### ISSUE THREAD

**Issue by patrolez** [DuffsDevice/tiny-utf8#63]
Hello,
while using object with `tiny_utf8::u8string` type there is a problem with compilation while `cpp_str()` and/or `cpp_str_bom()` is being in use by a code.

Compiler: `g++-10`, 10.3.0-1ubuntu1~20.04
With `-std=c++2a` flag.

```
../../libs/tiny-utf8/include/tinyutf8/tinyutf8.h:3404:46: error: conversion from ‘basic_string<char>’ to non-scalar type ‘basic_string<char8_t>’ requested
 3404 |   std::basic_string<data_type> result = std::string( size() + 3 , ' ' );
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

https://github.com/DuffsDevice/tiny-utf8/blob/cab426cc57686c418e422b0e2941a4ff5355bc72/include/tinyutf8/tinyutf8.h#L3404

**Comment by DuffsDevice** [comment]
Hi Patryk,

Thanks for submitting a bug report, I'll fix it right away!

**Comment by DuffsDevice** [comment]
Let me know, if everything works for you now. If not, please feel free to re-open the ticket :)
